### ISSUE TITLE
Can this implementation be utilized for 2D?

### ISSUE THREAD

**Issue by ogencoglu** [nstucki/Betti-Matching-3D#6]
Or does https://github.com/nstucki/Betti-matching/tree/master have a faster implementation?

**Comment by nstucki** [comment]
Yes, it includes specific and optimised implementations for 1D, 2D and 3D and its 2D implementation is faster than https://github.com/nstucki/Betti-matching/tree/master. Additionally it contains an implementation for arbitrary dimensions, which is less efficient.
